from django.urls import path
from .views import (
    AdminMenuView,
    AllProductsView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ManufacturerCreateView,
    ManufacturerUpdateView,
    ManufacturerDeleteView,
    CustomerListView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
    OrderListView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ReviewListView,
    ReviewCreateView,
    ReviewUpdateView,
    ReviewDeleteView,
    UserManagementView,
    UserCreateView,
    UserDeleteView,
    user_update,
    home,
    about,
    contacts,
    find_us,
    products,
    categories,
    cart,
    add_to_cart,
    update_cart,
    remove_from_cart,
    create_order,
    custom_logout,
    OrderManagementView,
    category_products,
    custom_404,
    custom_500
)

urlpatterns = [
    path('home/', home, name='home'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('find_us/', find_us, name='find_us'),
    path('products/', products, name='products'),
    path('categories/', categories, name='categories'),
    path('categories/<slug:slug>/', category_products, name='category_products'),
    path('all-products/', AllProductsView.as_view(), name='all_products'),
    path('cart/', cart, name='cart'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/<int:product_id>/', update_cart, name='update_cart'),
    path('cart/remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart/create_order/', create_order, name='create_order'),
    path('admin/', AdminMenuView.as_view(), name='admin_dashboard'),
    path('admin/categories/', CategoryListView.as_view(), name='category_crud'),
    path('admin/categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('admin/categories/<slug:slug>/', CategoryUpdateView.as_view(), name='category_update'),
    path('admin/categories/<slug:slug>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('admin/products/', ProductListView.as_view(), name='product_crud'),
    path('admin/products/create/', ProductCreateView.as_view(), name='product_create'),
    path('admin/products/<slug:slug>/', ProductUpdateView.as_view(), name='product_update'),
    path('admin/products/<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('admin/manufacturers/create/', ManufacturerCreateView.as_view(), name='manufacturer_create'),
    path('admin/manufacturers/<int:pk>/', ManufacturerUpdateView.as_view(), name='manufacturer_update'),
    path('admin/manufacturers/<int:pk>/delete/', ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
    path('admin/customers/', CustomerListView.as_view(), name='customer_crud'),
    path('admin/customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('admin/customers/<int:pk>/', CustomerUpdateView.as_view(), name='customer_update'),
    path('admin/customers/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('admin/orders/', OrderListView.as_view(), name='order_crud'),
    path('admin/orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('admin/orders/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('admin/orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('admin/reviews/', ReviewListView.as_view(), name='review_crud'),
    path('admin/reviews/create/', ReviewCreateView.as_view(), name='review_create'),
    path('admin/reviews/<int:pk>/', ReviewUpdateView.as_view(), name='review_update'),
    path('admin/reviews/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    path('admin/users/', UserManagementView.as_view(), name='user_management'),
    path('admin/users/create/', UserCreateView.as_view(), name='user_create'),
    path('admin/users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
    path('admin/users/<int:pk>/update/', user_update, name='user_update'),
    path('admin/order-management/', OrderManagementView.as_view(), name='order_management'),
    path('admin/order/<int:pk>/', OrderManagementView.as_view(), name='order_details'),
    path('logout/', custom_logout, name='logout'),
]