from django.urls import path
from .views import (
    AdminMenuView,
    AllProductsView,
    CategoryCRUDView,
    ProductCRUDView,
    CustomerCRUDView,
    OrderCRUDView,
    ReviewCRUDView,
    home,
    about,
    contacts,
    find_us,
    products,
    categories,
    cart
)

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    path('find-us/', find_us, name='find_us'),
    path('products/', products, name='products'),
    path('categories/', categories, name='categories'),
    path('all-products/', AllProductsView.as_view(), name='all_products'),
    path('cart/', cart, name='cart'),
    path('admin/', AdminMenuView.as_view(), name='admin_dashboard'),
    path('admin/categories/', CategoryCRUDView.as_view(), name='category_crud'),
    path('admin/categories/<slug:slug>/', CategoryCRUDView.as_view(), name='category_crud'),
    path('admin/products/', ProductCRUDView.as_view(), name='product_crud'),
    path('admin/products/<slug:slug>/', ProductCRUDView.as_view(), name='product_crud'),
    path('admin/products/<int:manufacturer_id>/', ProductCRUDView.as_view(), name='product_crud'),
    path('admin/customers/', CustomerCRUDView.as_view(), name='customer_crud'),
    path('admin/customers/<int:pk>/', CustomerCRUDView.as_view(), name='customer_crud'),
    path('admin/orders/', OrderCRUDView.as_view(), name='order_crud'),
    path('admin/orders/<int:pk>/', OrderCRUDView.as_view(), name='order_crud'),
    path('admin/reviews/', ReviewCRUDView.as_view(), name='review_crud'),
    path('admin/reviews/<int:pk>/', ReviewCRUDView.as_view(), name='review_crud'),
]