# Generated by Django 5.2.2 on 2025-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_category_image_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
